### ISSUE TITLE
Horses teleport when dismounted

### ISSUE THREAD

**Issue by NoeLoisil** [TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2#44] opened 2022-11-26 19:07 UTC
### Version modpack Used

Default

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

After dismounting a horse, I expect the dismount the horse while the horse goes around with his normal ai

### Actual Behavior

After dismounting a horse after a long journey, the horse either:
- have the expected behavior
- glide for 10-50 blocks at high speed
- teleport

### Steps to Reproduce

1) tame a horse
2) travel far away
3) dismount it

### Additional Information

Modpack version 4.1.8
The horse has the max tame rate for a naturally spawning one
Putting a lead on the horse stops it from gliding
The farther you travel, the higher is the chance of the bug occurring (I'm not sure, I don't have a large sample of test)

**Comment by Xikaro** [comment] 2022-11-26 19:37
I think this lag is caused by the computer itself

**Comment by NoeLoisil** [comment] 2022-11-27 02:13
It's still strange that a horse glide after being dismounted, I will try to record it and send the video here

**Comment by Xikaro** [comment] 2023-03-08 20:21
I'll close this for now because I think it's a minecraft issue.

**Closed by Xikaro** 2023-03-08 20:21 UTC
Labels: type: bug, status: cannot reproduce
